// ================================================================
// HexaCube Instrument Configuration
// Generated by HexaCube Config Tool — copy to Source/Shared/InstrumentData.h
// ================================================================

#pragma once

static const char* const INSTRUMENT_NAMES[16] =
{
    /* 00 */ "Bass (Factory)",
    /* 01 */ "Bass (voXager)",
    /* 02 */ "Snare (Factory)",
    /* 03 */ "Snare (voXager)",
    /* 04 */ "Tom XH",
    /* 05 */ "Tom H (Factory)",
    /* 06 */ "Tom M (Factory)",
    /* 07 */ "Tom L (Factory)",
    /* 08 */ "Tom XH (voXager)",
    /* 09 */ "Tom H (voXager)",
    /* 10 */ "Tom M (voXager)",
    /* 11 */ "Tom L (voXager)",
    /* 12 */ "HH Close",
    /* 13 */ "HH Open",
    /* 14 */ "Splash",
    /* 15 */ "Block",
};

// Instrument indices in display order
static const int DISPLAY_ORDER[16] = { 0, 2, 7, 6, 5, 4, 1, 3, 8, 9, 10, 11, 12, 13, 14, 15 };

// Default MIDI note assignments
static const int DEFAULT_MIDI_NOTES[16] =
{
    /* 00 "Bass (Factory)" */ 36,
    /* 01 "Bass (voXager)" */ 48,
    /* 02 "Snare (Factory)" */ 38,
    /* 03 "Snare (voXager)" */ 50,
    /* 04 "Tom XH" */ 40,
    /* 05 "Tom H (Factory)" */ 41,
    /* 06 "Tom M (Factory)" */ 43,
    /* 07 "Tom L (Factory)" */ 45,
    /* 08 "Tom XH (voXager)" */ 52,
    /* 09 "Tom H (voXager)" */ 53,
    /* 10 "Tom M (voXager)" */ 55,
    /* 11 "Tom L (voXager)" */ 57,
    /* 12 "HH Close" */ 42,
    /* 13 "HH Open" */ 46,
    /* 14 "Splash" */ 49,
    /* 15 "Block" */ 56,
};

// Cross-choke pairs: { source_instrument, choked_instrument }
// (source chokes target when triggered; self-choke is always implicit)
static const int CHOKE_PAIRS[][2] =
{
    { 12, 13 },  // "HH Close" chokes "HH Open"
    { -1, -1 }  // sentinel
};
